version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: travelnest-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: travelnest
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - travelnest-net

  redis:
    image: redis:7-alpine
    container_name: travelnest-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    networks:
      - travelnest-net

networks:
  travelnest-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
